import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en" className=" ">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Welcome to Sh's World 🚀</title>
      <link rel="shortcut icon" href="https://github.com/sh20raj.png" type="image/x-icon" />
    </head>
    <body>
      {children}
    </body>
    </html>

</>
  );
}
