/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TMtZbR12TC5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from "@/components/ui/context-menu"
import { useState, useEffect } from "react";


export function Main() {
  const [mode, setMode] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("theme") || "dark";
    }
    return "dark"; // Default to dark theme if localStorage is not available
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      document.documentElement.classList.toggle("dark", mode === "dark");
      localStorage.setItem("theme", mode);
    }
  }, [mode]);

  const toggle = () => setMode((prevMode) => (prevMode === "dark" ? "light" : "dark"));

  return (
    (        <ContextMenu>
  <ContextMenuTrigger>

<div className={"flex flex-col min-h-[100dvh]  "} >
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between">
        <Link className="flex items-center gap-2" href="#">
          <CodeIcon className="h-6 w-6" />
          <span className="font-semibold text-lg">SH20RAJ</span>
        </Link>

        <nav className="hidden lg:flex gap-6">
          <Link className="font-medium hover:underline underline-offset-4" href="#about">
            About
          </Link>
          <Link className="font-medium hover:underline underline-offset-4" href="#projects">
            Projects
          </Link>
          <Link className="font-medium hover:underline underline-offset-4" href="#skills">
            Skills
          </Link>
          <Link className="font-medium hover:underline underline-offset-4" href="#contact">
            Contact
          </Link>
        </nav>
        <Button className="lg:hidden" size="icon" variant="outline">
          <MenuIcon className="h-6 w-6" />
          <span className="sr-only">Toggle navigation</span>
        </Button>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48" id="hero">
          <div className="container px-4 md:px-6 grid gap-8 lg:grid-cols-2 items-center">
            <div className="space-y-4 text-center lg:text-left">
              <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Hi, I'm SH RAJ</h1>
              <p className="text-gray-500 md:text-xl dark:text-gray-400">
                I'm a passionate full-stack developer with expertise in modern web technologies.
              </p>
              <div className="flex justify-center lg:justify-start gap-4">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-6 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="https://github.com/sh20raj">
                  View Resume
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200  bg-white px-6 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                  href="https://x.com/sh20raj">
                  Contact Me
                </Link>
              </div>
            </div>
            <div className="flex justify-center">
              <img
                alt="SH20RAJ"
                className="rounded-full w-[300px] h-[300px] md:w-[400px] md:h-[400px] object-cover"
                height={400}
                src="https://github.com/sh20raj.png"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-950"
          id="about">
          <div className="container px-4 md:px-6 grid gap-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">About Me</h2>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                I'm a full-stack developer with a passion for building modern, responsive, and user-friendly web
                applications. I have extensive experience in various web technologies, including React, Node.js, and
                MongoDB.
              </p>
            </div>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <h3 className="text-xl font-bold">My Background</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  I have a Bachelor's degree in Computer Science and have been working as a professional developer for
                  the past 5 years. During this time, I've had the opportunity to work on a wide range of projects, from
                  small business websites to large-scale enterprise applications.
                </p>
              </div>
              <div className="space-y-4">
                <h3 className="text-xl font-bold">My Approach</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  I believe in a collaborative and iterative approach to software development. I work closely with my
                  clients to understand their needs and requirements, and then use my technical expertise to deliver
                  high-quality solutions that meet their goals. I'm also a strong believer in writing clean,
                  maintainable code and following best practices.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="projects">
          <div className="container px-4 md:px-6 grid gap-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">My Projects</h2>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Here are some of the projects I've worked on:
              </p>
            </div>
            <div className="grid lg:grid-cols-2 gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Ecommerce Platform</CardTitle>
                  <CardDescription>
                    A fully-featured ecommerce platform built with React, Node.js, and MongoDB.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500 dark:text-gray-400">
                    This project includes features such as product management, shopping cart, checkout, and order
                    tracking. It also has a responsive design and is optimized for performance.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link className="font-medium hover:underline" href="https://github.com/sh20raj">
                    View Project
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Blog Application</CardTitle>
                  <CardDescription>A modern blog application built with Next.js and Contentful.</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500 dark:text-gray-400">
                    This project features a clean and responsive design, dynamic content management, and advanced search
                    and filtering capabilities.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link className="font-medium hover:underline" href="https://github.com/sh20raj">
                    View Project
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Task Management App</CardTitle>
                  <CardDescription>
                    A task management application built with React, Firebase, and Material-UI.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500 dark:text-gray-400">
                    This project includes features such as task creation, assignment, and tracking, as well as real-time
                    collaboration and notifications.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link className="font-medium hover:underline" href="https://github.com/sh20raj">
                    View Project
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Personal Website</CardTitle>
                  <CardDescription>My personal website, built with Next.js and Tailwind CSS.</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500 dark:text-gray-400">
                    This website showcases my work, skills, and experience, and serves as a platform for me to share my
                    thoughts and ideas.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link className="font-medium hover:underline" href="https://github.com/sh20raj">
                    View Project
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-950"
          id="skills">
          <div className="container px-4 md:px-6 grid gap-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">My Skills</h2>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Here are some of the technologies I'm proficient in:
              </p>
            </div>
            <div
              className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-6">
              <div className="flex flex-col items-center gap-2">
                <ComponentIcon className="w-10 h-10" />
                <span className="text-sm font-medium">React</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <NetworkIcon className="w-10 h-10" />
                <span className="text-sm font-medium">Node.js</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <DatabaseIcon className="w-10 h-10" />
                <span className="text-sm font-medium">MongoDB</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <ChromeIcon className="w-10 h-10" />
                <span className="text-sm font-medium">JavaScript</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <TypeIcon className="w-10 h-10" />
                <span className="text-sm font-medium">TypeScript</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <WindIcon className="w-10 h-10" />
                <span className="text-sm font-medium">Tailwind CSS</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <FolderGitIcon className="w-10 h-10" />
                <span className="text-sm font-medium">Git</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <ContainerIcon className="w-10 h-10" />
                <span className="text-sm font-medium">Docker</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <CloudIcon className="w-10 h-10" />
                <span className="text-sm font-medium">AWS</span>
              </div>
              <div className="flex flex-col items-center gap-2">
                <FacebookIcon className="w-10 h-10" />
                <span className="text-sm font-medium">Firebase</span>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="contact">
          <div className="container px-4 md:px-6 grid gap-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Get in Touch</h2>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                I'd love to hear from you! Feel free to reach out with any questions or opportunities.
              </p>
            </div>
            <div className="mx-auto w-full max-w-md space-y-4">
              <form className="space-y-4" action={"https://x.com/sh20raj"}>
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" required type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" required rows={5} />
                </div>
                <Button className="w-full" type="submit">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 SH20RAJ. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="https://github.com/sh20raj">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://github.com/sh20raj">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
    
    </ContextMenuTrigger>
  <ContextMenuContent>
    <ContextMenuItem><Link target="_" href="https://github.com/sh20raj">GitHub</Link></ContextMenuItem>
    <ContextMenuItem><Link target="_" href="https://codepen.com/sh20raj">Codepen</Link></ContextMenuItem>
    <ContextMenuItem><Link target="_" href="https://x.com/sh20raj">Twitter</Link></ContextMenuItem>
    <ContextMenuItem><Link target="_" href="https://dev.to/sh20raj">Dev.to</Link></ContextMenuItem>
    <ContextMenuItem><Link target="_" href="https://sh20raj.com/#projects">Projects</Link></ContextMenuItem>
    <ContextMenuSeparator/>
    <ContextMenuItem><Link href="#" onClick={()=>toggle(!mode)}>Change Mode</Link></ContextMenuItem>
  </ContextMenuContent>
</ContextMenu>
)
  );
}

function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}


function CloudIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function ComponentIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>)
  );
}


function ContainerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 7.7c0-.6-.4-1.2-.8-1.5l-6.3-3.9a1.72 1.72 0 0 0-1.7 0l-10.3 6c-.5.2-.9.8-.9 1.4v6.6c0 .5.4 1.2.8 1.5l6.3 3.9a1.72 1.72 0 0 0 1.7 0l10.3-6c.5-.3.9-1 .9-1.5Z" />
      <path d="M10 21.9V14L2.1 9.1" />
      <path d="m10 14 11.9-6.9" />
      <path d="M14 19.8v-8.1" />
      <path d="M18 17.5V9.4" />
    </svg>)
  );
}


function DatabaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function FolderGitIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z" />
      <circle cx="12" cy="13" r="2" />
      <path d="M14 13h3" />
      <path d="M7 13h3" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function NetworkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>)
  );
}


function TypeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>)
  );
}


function WindIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>)
  );
}
